"""阶段 B：按清单生成 pytest 代码。mock=确定性模板渲染；real=LLM 生成后语法校验。"""

from __future__ import annotations

import ast
import builtins
import logging
from typing import Any

from pydantic import BaseModel

from services.shared.llm import LLMClient, mock_task
from services.testgen_svc.schemas import CasePlan, PlannedCase

log = logging.getLogger("testgen.codegen")


def _fmt_value(v: Any) -> str:
    return repr(v)


def _mod_var(module: str) -> str:
    """app.inventory.client → inventory_client（避免多个 *.client 同名冲突）。"""
    return module.replace(".", "_")


def render_case_body(case: PlannedCase, target_fn: str, error_cls: str) -> str:
    """单个用例 → pytest 测试函数源码。"""
    fname = f"test_{case.id.lower().replace('-', '')}_{_slug(case.title)}"
    kw = ", ".join(f"{k}={_fmt_value(v)}" for k, v in case.input.items())
    lines: list[str] = [f"def {fname}(monkeypatch):"]

    for p in case.patches:
        var = _mod_var(p.module)
        if p.kind == "raise":
            lines.append(f"    from {p.exc_module} import {p.exc}")
            lines.append(f'    monkeypatch.setattr({var}, "{p.attr}", _raise({p.exc}()))')
        else:
            lines.append(f'    monkeypatch.setattr({var}, "{p.attr}", lambda *a, **k: {_fmt_value(p.value)})')

    call = f"{target_fn}({kw})"
    idem = "idempotency_key" in case.input

    if case.expected_error or case.expected_error_type:
        exc_cls = case.expected_error_type or error_cls
        lines.append("    with pytest.raises(" + exc_cls + ") as ei:")
        lines.append(f"        {call}")
        if case.expected_error:
            if case.guard_added:
                lines.append(f'    assert "{case.expected_error}" in ei.value.code')
            else:
                lines.append(f'    assert ei.value.code == "{case.expected_error}"')
    elif idem:
        lines.append(f"    o1 = {call}")
        lines.append(f"    o2 = {call}")
        lines.append('    assert o1["order_id"] == o2["order_id"]  # 幂等：不重复下单')
    elif case.guard_added and not (case.assert_return or case.expected_fields):
        lines.append("    try:")
        lines.append(f"        result = {call}")
        lines.append("        assert result is not None")
        lines.append(f"    except {error_cls}:")
        lines.append("        pass  # 极值输入被安全拒绝亦通过")
    else:
        lines.append(f"    result = {call}")
        hit = False
        if case.assert_return:
            hit = True
            lines.append(f"    assert result == {_fmt_value(case.expected_return)}")
        for s in case.expected_not_contains:
            hit = True
            lines.append(f"    assert {_fmt_value(s)} not in result")
        for s in case.expected_contains:
            hit = True
            lines.append(f"    assert {_fmt_value(s)} in result")
        for k, v in case.expected_fields.items():
            hit = True
            if isinstance(v, float):
                lines.append(f'    assert result["{k}"] == pytest.approx({_fmt_value(v)})')
            else:
                lines.append(f'    assert result["{k}"] == {_fmt_value(v)}')
        if not hit:
            lines.append("    assert result is not None")

    doc = f'    """{case.title}｜覆盖: {case.covers}"""\n' if case.covers else ""
    return doc + "\n".join(lines)


def _slug(title: str) -> str:
    keep = "".join(ch if (ch.isascii() and (ch.isalnum() or ch == "_")) else "_" for ch in title)
    return keep.strip("_").lower()[:40] or "case"


def render_file(plan: CasePlan, target_module: str, target_fn: str, error_cls: str, gen_code: str) -> str:
    """整文件渲染：header（imports + _raise 助手）+ 每用例函数。"""
    # 约定错误类若是内建异常（ValueError/TypeError…），从 builtins 导入而非被测模块
    err_from_module = not hasattr(builtins, error_cls)
    imports = {"import pytest", f"from {target_module} import {target_fn}"}
    if err_from_module:
        imports.add(f"from {target_module} import {error_cls}")
    else:
        imports.add(f"from builtins import {error_cls}")
    for m in sorted({p.module for c in plan.cases for p in c.patches}):
        imports.add(f"import {m} as {_mod_var(m)}")

    header = [
        f'"""AUTO-GENERATED by TestForge · gen={gen_code} · target={target_module}.{target_fn}',
        "",
        "两阶段生成产物：阶段A清单(plan+guard) → 阶段B按清单渲染。请勿手改。",
        '"""',
        *sorted(imports),
        "",
        "",
        "def _raise(exc):",
        "    def _f(*a, **k):",
        "        raise exc",
        "",
        "    return _f",
    ]
    bodies = [render_case_body(c, target_fn, error_cls) for c in plan.cases]
    return "\n".join(header) + "\n\n\n" + "\n\n\n".join(bodies) + "\n"


class CodeFile(BaseModel):
    """real 模式 LLM 输出 schema。"""

    code: str


def codegen(llm: LLMClient, plan: CasePlan, gen_code: str) -> str:
    """两阶段之阶段 B：按清单生成代码。"""
    target_module = plan.module or _infer_module(plan.target)
    target_fn = plan.target.split(".")[-1]
    error_cls = _error_cls_for(target_module, target_fn)
    if llm.is_mock:
        return render_file(plan, target_module, target_fn, error_cls, gen_code)
    # real：LLM 按清单生成，本地语法校验
    prompt = (
        f"{mock_task('codegen')}\n按以下用例清单生成一个完整 pytest 文件（目标 {target_module}.{target_fn}，"
        f"错误类 {error_cls}）。只返回 JSON：{{\"code\": \"<整文件python源码>\"}}\n"
        f"清单：{plan.model_dump_json()[:8000]}"
    )
    out = llm.chat_json([{"role": "user", "content": prompt}], schema=CodeFile, mock=None)
    try:
        ast.parse(out.code)
    except SyntaxError as exc:
        raise ValueError(f"生成的代码语法错误: {exc}") from exc
    return out.code


def _infer_module(target: str) -> str:
    return target.rsplit(".", 1)[0] if "." in target else ""


def _error_cls_for(module: str, fn: str) -> str:
    """业务异常类约定：仓库源码中以 <Domain>Error 命名；按模块/函数名启发。"""
    return "OrderError" if "order" in (module + fn).lower() else "ValueError"
