"""接口层 / E2E 层用例渲染：按清单确定性生成 pytest（httpx 对真实服务执行）。

与 codegen 同构：阶段 A 清单（webplan）→ 阶段 B 按清单渲染，请勿手改产物。
接口用例断言来自实时 OpenAPI 契约；E2E 旅程断言跨步骤真实数据关系。
"""

from __future__ import annotations

import json
from typing import Any

from services.testgen_svc.schemas import CasePlan, PlannedCase

HEADER = '''\
"""AUTO-GENERATED by TestForge · gen=__GEN__ · layer=__LAYER__

__LAYER_DESC__产物：期望值来自实时契约与旅程设计，对真实运行的服务执行。请勿手改。
"""
import os

import httpx
import pytest

BASE = os.environ.get("TF_API_BASE_URL", "__BASE__")
ADMIN_PASSWORD = os.environ.get("TF_ADMIN_PASSWORD", "testforge-admin")
TIMEOUT = 15

_token_cache = None


def _token():
    global _token_cache
    if _token_cache is None:
        r = httpx.post(
            f"{BASE}/api/auth/login",
            json={"username": "admin", "password": ADMIN_PASSWORD},
            timeout=TIMEOUT,
        )
        assert r.status_code == 200, "测试登录失败: %s %s" % (r.status_code, r.text[:200])
        _token_cache = {"Authorization": "Bearer " + r.json()["data"]["token"]}
    return _token_cache


def _dig(obj, dotted):
    """按 a.b.c 取嵌套键（存在性断言用）。"""
    cur = obj
    for part in dotted.split("."):
        cur = cur[part]
    return cur
'''


def _slug(title: str) -> str:
    keep = "".join(ch if (ch.isascii() and (ch.isalnum() or ch == "_")) else "_" for ch in title)
    return keep.strip("_").lower()[:40] or "case"


def _status_expr(expect_status: Any) -> str:
    if isinstance(expect_status, (list, tuple)):
        return f"in {repr(tuple(expect_status))}"
    return f"== {int(expect_status)}"


def _request_expr(method: str, path: str, step: dict, token_var: str | None) -> str:
    args = [f'f"{{BASE}}{path}"']
    if step.get("json_body") is not None:
        body = json.dumps(step["json_body"], ensure_ascii=False)
        if "__env_password__" in body:
            body = '{"username": "admin", "password": ADMIN_PASSWORD}'
        args.append(f"json={body}")
    if step.get("auth"):
        args.append(
            'headers={"Authorization": "Bearer " + TOKEN}' if token_var else "headers=_token()"
        )
    args.append("timeout=TIMEOUT")
    joined = ", ".join(args)
    return f"httpx.request({method!r}, {joined})"


def _render_api_case(case: PlannedCase) -> str:
    inp = case.input
    method = str(inp.get("method", "GET"))
    path = str(inp.get("path", "/"))
    lines = [f"def test_{case.id.lower().replace('-', '')}_{_slug(case.title)}():"]
    if case.covers:
        lines.append(f'    """{case.title}｜覆盖: {case.covers}"""')
    lines.append(f"    r = {_request_expr(method, path, inp, None)}")
    lines.append(f"    assert r.status_code {_status_expr(inp.get('expect_status', 200))}")
    if inp.get("expect_code") is not None or inp.get("expect_keys"):
        lines.append("    body = r.json()")
    if inp.get("expect_code") is not None:
        lines.append(f"    assert body.get('code') == {int(inp['expect_code'])}")
    for dotted in inp.get("expect_keys") or []:
        lines.append(f"    _dig(body, {dotted!r})  # 键存在性（契约结构断言）")
    return "\n".join(lines)


def _render_e2e_case(case: PlannedCase) -> str:
    inp = case.input
    lines = [f"def test_{case.id.lower().replace('-', '')}_{_slug(case.title)}():"]
    if case.covers:
        lines.append(f'    """{case.title}｜覆盖: {case.covers}"""')
    token_var: str | None = None
    for i, step in enumerate(inp.get("steps") or [], 1):
        method = str(step.get("method", "GET"))
        path = str(step.get("path", "/"))
        lines.append(f"    r{i} = {_request_expr(method, path, step, token_var)}")
        lines.append(f"    assert r{i}.status_code {_status_expr(step.get('expect_status', 200))}")
        save = str(step.get("save") or "")
        if "->" in save:
            dotted, var = (s.strip() for s in save.split("->", 1))
            lines.append(f"    {var} = _dig(r{i}.json(), {dotted!r})")
            if var == "TOKEN":
                token_var = var
    for assertion in inp.get("final_asserts") or []:
        lines.append(f"    assert {assertion}")
    return "\n".join(lines)


def render_web_file(plan: CasePlan, gen_code: str) -> str:
    """整文件渲染：header（httpx 基座 + 登录助手）+ 每用例函数。"""
    layer = plan.layer or "api"
    layer_desc = {
        "api": "接口层用例（实时 OpenAPI 契约推导，对真实服务发起 HTTP 调用）",
        "e2e": "E2E 旅程用例（跨端点多步真实调用链，断言跨步骤数据关系）",
    }.get(layer, "Web 层用例")
    base = (plan.cases[0].input.get("base_url") if plan.cases else None) or ""
    header = (
        HEADER.replace("__GEN__", gen_code)
        .replace("__LAYER__", layer)
        .replace("__LAYER_DESC__", layer_desc)
        .replace("__BASE__", base)
    )
    parts = [header]
    for case in plan.cases:
        parts.append(_render_e2e_case(case) if layer == "e2e" else _render_api_case(case))
    return "\n\n\n".join(parts) + "\n"
